using AssignmentManagement.Core.Enums;
using AssignmentManagement.Core.Models.Entities;
using AssignmentManagement.Infrastructure.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace AssignmentManagement.WebAPI;

public static class DatabaseInitializer
{
    public static async Task InitializeAsync(
        IServiceProvider services,
        IConfiguration configuration,
        ILogger logger)
    {
        await using var scope = services.CreateAsyncScope();
        var dbContext = scope.ServiceProvider.GetRequiredService<AssignmentDbContext>();

        var autoCreate = configuration.GetValue("Database:AutoCreate", true);
        if (autoCreate)
        {
            logger.LogInformation("Ensuring PostgreSQL database and tables exist...");
            await dbContext.Database.EnsureCreatedAsync();
        }

        if (!await dbContext.Database.CanConnectAsync())
            throw new InvalidOperationException("Cannot connect to PostgreSQL. Check the connection string and PostgreSQL service.");

        await EnsureSchemaUpgradesAsync(dbContext);
        await SeedRolesAsync(dbContext);
        var institution = await SeedInstitutionAsync(dbContext, configuration);
        await SeedSettingsAsync(dbContext, institution.Id);
        await SeedAdminAsync(dbContext, configuration, institution.Id);
    }

    private static Task EnsureSchemaUpgradesAsync(AssignmentDbContext dbContext) =>
        dbContext.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS "PasswordResetCodes" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "CodeHash" character varying(128) NOT NULL,
                "ExpiresAtUtc" timestamp with time zone NOT NULL,
                "UsedAtUtc" timestamp with time zone,
                "FailedAttempts" integer NOT NULL DEFAULT 0,
                "UserId" bigint NOT NULL,
                "CreatedAtUtc" timestamp with time zone NOT NULL,
                "CreatedByUserId" bigint,
                "UpdatedAtUtc" timestamp with time zone,
                "UpdatedByUserId" bigint,
                "IsActive" boolean NOT NULL,
                CONSTRAINT "FK_PasswordResetCodes_Users_UserId"
                    FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
            );
            CREATE INDEX IF NOT EXISTS "IX_PasswordResetCodes_UserId_CreatedAtUtc"
                ON "PasswordResetCodes" ("UserId", "CreatedAtUtc");

            ALTER TABLE "Assignments"
                ADD COLUMN IF NOT EXISTS "AllowFileUpload" boolean NOT NULL DEFAULT false,
                ADD COLUMN IF NOT EXISTS "AllowLateSubmission" boolean NOT NULL DEFAULT false,
                ADD COLUMN IF NOT EXISTS "RequireFeedbackForGrading" boolean NOT NULL DEFAULT false,
                ADD COLUMN IF NOT EXISTS "ShowGradesImmediately" boolean NOT NULL DEFAULT false;

            ALTER TABLE "Submissions"
                ADD COLUMN IF NOT EXISTS "FileName" character varying(255),
                ADD COLUMN IF NOT EXISTS "StoredFilePath" character varying(500),
                ADD COLUMN IF NOT EXISTS "FileContentType" character varying(100),
                ADD COLUMN IF NOT EXISTS "FileSize" bigint;
            """);

    private static async Task SeedRolesAsync(AssignmentDbContext dbContext)
    {
        foreach (var roleName in AppRoles.All)
        {
            if (!await dbContext.Roles.AnyAsync(x => x.Name == roleName))
                dbContext.Roles.Add(new AppRole { Name = roleName });
        }

        await dbContext.SaveChangesAsync();
    }

    private static async Task<Institution> SeedInstitutionAsync(
        AssignmentDbContext dbContext,
        IConfiguration configuration)
    {
        var code = (configuration["Seed:InstitutionCode"] ?? "DEMO").Trim().ToUpperInvariant();
        var institution = await dbContext.Institutions.FirstOrDefaultAsync(x => x.Code == code);
        if (institution is not null)
            return institution;

        var typeText = configuration["Seed:InstitutionType"] ?? nameof(InstitutionType.College);
        if (!Enum.TryParse<InstitutionType>(typeText, true, out var institutionType))
            institutionType = InstitutionType.College;

        institution = new Institution
        {
            Name = configuration["Seed:InstitutionName"] ?? "Demo College",
            Code = code,
            Type = institutionType,
            Address = configuration["Seed:InstitutionAddress"],
            Email = configuration["Seed:InstitutionEmail"],
            Phone = configuration["Seed:InstitutionPhone"]
        };
        dbContext.Institutions.Add(institution);
        await dbContext.SaveChangesAsync();
        return institution;
    }

    private static async Task SeedSettingsAsync(AssignmentDbContext dbContext, long institutionId)
    {
        var settings = ApplicationSettingCatalog.Definitions
            .Where(x => x.SeedByDefault)
            .Select(x => new ApplicationSetting
            {
                InstitutionId = institutionId,
                Key = x.Key,
                Value = x.DefaultValue ? "true" : "false",
                Description = x.Description
            });

        foreach (var setting in settings)
        {
            if (!await dbContext.ApplicationSettings.AnyAsync(
                    x => x.InstitutionId == institutionId && x.Key == setting.Key))
                dbContext.ApplicationSettings.Add(setting);
        }

        await dbContext.SaveChangesAsync();
    }

    private static async Task SeedAdminAsync(
        AssignmentDbContext dbContext,
        IConfiguration configuration,
        long institutionId)
    {
        var userName = (configuration["Seed:AdminUserName"] ?? "admin").Trim().ToLowerInvariant();
        var email = (configuration["Seed:AdminEmail"] ?? "admin@demo.local").Trim().ToLowerInvariant();
        var password = configuration["Seed:AdminPassword"] ?? "Admin@123";

        var admin = await dbContext.Users
            .Include(x => x.UserRoles)
            .FirstOrDefaultAsync(x => x.UserName == userName);

        if (admin is null)
        {
            admin = new AppUser
            {
                FullName = configuration["Seed:AdminFullName"] ?? "System Admin",
                UserName = userName,
                Email = email,
                InstitutionId = institutionId
            };
            var passwordHasher = new PasswordHasher<AppUser>();
            admin.PasswordHash = passwordHasher.HashPassword(admin, password);
            dbContext.Users.Add(admin);
            await dbContext.SaveChangesAsync();
        }

        var adminRoleId = await dbContext.Roles
            .Where(x => x.Name == AppRoles.Admin)
            .Select(x => x.Id)
            .SingleAsync();

        if (!await dbContext.UserRoles.AnyAsync(x => x.UserId == admin.Id && x.RoleId == adminRoleId))
        {
            dbContext.UserRoles.Add(new UserRole { UserId = admin.Id, RoleId = adminRoleId });
            await dbContext.SaveChangesAsync();
        }
    }
}
