"use client";

import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Building2, KeyRound, Mail, ShieldCheck, UserRound } from "lucide-react";
import { z } from "zod";
import { toast } from "sonner";
import { useAuth } from "@/components/auth/auth-provider";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { PageHeader } from "@/components/ui/page-header";
import { authService } from "@/lib/services";
import { errorMessage, getInitials } from "@/lib/utils";

const schema=z.object({currentPassword:z.string().min(1,"Current password is required"),newPassword:z.string().min(8,"New password must be at least 8 characters"),confirmPassword:z.string().min(1,"Confirm your new password")}).refine(v=>v.newPassword===v.confirmPassword,{path:["confirmPassword"],message:"Passwords do not match"});type FormValues=z.infer<typeof schema>;
export default function ProfilePage(){const{session,logout}=useAuth();const form=useForm<FormValues>({resolver:zodResolver(schema),defaultValues:{currentPassword:"",newPassword:"",confirmPassword:""}});const save=async(v:FormValues)=>{try{await authService.changePassword({currentPassword:v.currentPassword,newPassword:v.newPassword});toast.success("Password changed. Please sign in again.");await logout();}catch(e){toast.error(errorMessage(e));}};if(!session)return null;return <><PageHeader title="Profile & security" description="View your account details and update your password."/><div className="grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><Card><CardContent className="p-6"><div className="flex h-20 w-20 items-center justify-center rounded-3xl bg-gradient-to-br from-indigo-500 to-sky-500 text-2xl font-black text-white">{getInitials(session.user.fullName)}</div><h2 className="mt-5 text-2xl font-black">{session.user.fullName}</h2><p className="mt-1 text-sm text-slate-500">@{session.user.userName}</p><div className="mt-4 flex flex-wrap gap-2">{session.user.roles.map(r=><Badge key={r} tone="indigo">{r}</Badge>)}</div><div className="mt-6 space-y-4 border-t border-slate-100 pt-5"><Line icon={Mail} label="Email" value={session.user.email}/><Line icon={Building2} label="Institution" value={session.user.institutionName}/>{session.user.academicClassName&&<Line icon={ShieldCheck} label="Class / course" value={session.user.academicClassName}/>}</div></CardContent></Card><Card><CardHeader><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-rose-50 text-rose-600"><KeyRound className="h-5 w-5"/></div><div><h2 className="font-extrabold">Change password</h2><p className="text-sm text-slate-500">You will be signed out after changing it.</p></div></div></CardHeader><CardContent><form className="space-y-4" onSubmit={form.handleSubmit(save)}><div><label className="field-label">Current password</label><Input type="password" {...form.register("currentPassword")}/>{form.formState.errors.currentPassword&&<p className="field-error">{form.formState.errors.currentPassword.message}</p>}</div><div className="grid gap-4 sm:grid-cols-2"><div><label className="field-label">New password</label><Input type="password" {...form.register("newPassword")}/>{form.formState.errors.newPassword&&<p className="field-error">{form.formState.errors.newPassword.message}</p>}</div><div><label className="field-label">Confirm password</label><Input type="password" {...form.register("confirmPassword")}/>{form.formState.errors.confirmPassword&&<p className="field-error">{form.formState.errors.confirmPassword.message}</p>}</div></div><div className="flex justify-end"><Button type="submit" loading={form.formState.isSubmitting}><KeyRound className="h-4 w-4"/> Change password</Button></div></form></CardContent></Card></div></>}
function Line({icon:Icon,label,value}:{icon:React.ComponentType<{className?:string}>;label:string;value:string}){return <div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-slate-100 text-slate-500"><Icon className="h-4 w-4"/></div><div><p className="text-xs font-semibold text-slate-400">{label}</p><p className="text-sm font-bold text-slate-700">{value}</p></div></div>}
