"use client";

import { useCallback, useEffect, useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Award, Download, Eye, Paperclip, Search } from "lucide-react";
import { z } from "zod";
import { toast } from "sonner";
import { SubmissionStatusBadge } from "@/components/common/status-badges";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { Input } from "@/components/ui/input";
import { InlineLoader } from "@/components/ui/loading";
import { Modal } from "@/components/ui/modal";
import { PageHeader } from "@/components/ui/page-header";
import { Pagination } from "@/components/ui/pagination";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { submissionService } from "@/lib/services";
import { defaultPageSize, submissionStatusLabel } from "@/lib/constants";
import { SubmissionStatus, type SubmissionResponse } from "@/lib/types";
import { errorMessage, formatDate } from "@/lib/utils";

const reviewSchema=z.object({marks:z.string().optional(),feedback:z.string().max(5000).optional(),status:z.string().min(1)});type ReviewForm=z.infer<typeof reviewSchema>;
const teacherReviewStatuses: SubmissionStatus[] = [
 SubmissionStatus.UnderReview,
 SubmissionStatus.Graded,
 SubmissionStatus.Returned,
];

export function SubmissionListPage({mode}:{mode:"admin"|"teacher"|"student"}){
 const[items,setItems]=useState<SubmissionResponse[]>([]);const[loading,setLoading]=useState(true);const[page,setPage]=useState(1);const[totalPages,setTotalPages]=useState(0);const[totalCount,setTotalCount]=useState(0);const[search,setSearch]=useState("");const[status,setStatus]=useState("");const[assignmentId,setAssignmentId]=useState("");const[selected,setSelected]=useState<SubmissionResponse|null>(null);const[fileAction,setFileAction]=useState<"view"|"download"|null>(null);
 const form=useForm<ReviewForm>({resolver:zodResolver(reviewSchema),defaultValues:{marks:"",feedback:"",status:String(SubmissionStatus.UnderReview)}});
 useEffect(()=>{if(typeof window!=="undefined"){setAssignmentId(new URLSearchParams(window.location.search).get("assignmentId")??"");}},[]);
 const load=useCallback(async()=>{setLoading(true);try{const r=await submissionService.get({pageNumber:page,pageSize:defaultPageSize,search:search||undefined,status:status?status as SubmissionStatus:undefined,assignmentId:assignmentId?Number(assignmentId):undefined});setItems(r.items);setTotalPages(r.totalPages);setTotalCount(r.totalCount);}catch(e){toast.error(errorMessage(e));}finally{setLoading(false);}},[assignmentId,page,search,status]);useEffect(()=>{void load();},[load]);
 const openReview=(item:SubmissionResponse)=>{setSelected(item);form.reset({marks:item.marks?.toString()??"",feedback:item.feedback??"",status:teacherReviewStatuses.includes(item.status)?String(item.status):String(SubmissionStatus.UnderReview)});};
 const review=async(v:ReviewForm)=>{if(!selected)return;const marks=v.marks===""?null:Number(v.marks);if(marks!=null&&(marks<0||marks>selected.assignmentMaximumMarks)){form.setError("marks",{message:`Marks must be between 0 and ${selected.assignmentMaximumMarks}`});return;}const feedbackRequired=v.status===SubmissionStatus.Returned||(v.status===SubmissionStatus.Graded&&selected.feedbackRequiredForGrading);if(feedbackRequired&&!v.feedback?.trim()){form.setError("feedback",{message:"Feedback is required for this review status"});return;}try{await submissionService.review(selected.id,{marks,feedback:v.feedback||null,status:v.status as SubmissionStatus});toast.success("Submission reviewed");setSelected(null);await load();}catch(e){toast.error(errorMessage(e));}};
 const handleFile=async(action:"view"|"download")=>{if(!selected?.fileName)return;setFileAction(action);try{if(action==="view")await submissionService.viewFile(selected.id);else await submissionService.downloadFile(selected.id,selected.fileName);}catch(e){toast.error(errorMessage(e));}finally{setFileAction(null);}};
 const title=mode==="student"?"My submissions":mode==="teacher"?"Student submissions":"All submissions";const description=mode==="student"?"Track your answers, marks and teacher feedback.":mode==="teacher"?"Review student work and provide marks and feedback.":"Monitor submission activity across the institution.";
 return <><PageHeader title={title} description={description}/><Card><div className="grid gap-3 border-b border-slate-100 p-4 md:grid-cols-3"><div className="relative"><Search className="absolute left-3.5 top-3.5 h-4 w-4 text-slate-400"/><Input className="pl-10" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Search student or assignment..."/></div><Input value={assignmentId} onChange={e=>{setAssignmentId(e.target.value.replace(/\D/g,""));setPage(1);}} placeholder="Filter by assignment ID"/><Select value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">All statuses</option>{Object.entries(submissionStatusLabel).map(([value,label])=><option key={value} value={value}>{label}</option>)}</Select></div>
 {loading?<InlineLoader/>:items.length===0?<EmptyState title="No submissions found" description="No records match your current filters."/>:<div className="overflow-x-auto"><table className="w-full min-w-[950px]"><thead className="table-head"><tr><th className="px-4 py-3">Assignment</th>{mode!=="student"&&<th className="px-4 py-3">Student</th>}<th className="px-4 py-3">Submitted</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Marks</th><th className="px-4 py-3">File</th><th className="px-4 py-3">Feedback</th>{mode==="teacher"&&<th className="px-4 py-3 text-right">Review</th>}</tr></thead><tbody>{items.map(item=><tr key={item.id} className="hover:bg-slate-50"><td className="table-cell"><p className="max-w-xs truncate font-bold text-slate-800">{item.assignmentTitle}</p><p className="mt-1 text-xs text-slate-500">Assignment #{item.assignmentId}</p></td>{mode!=="student"&&<td className="table-cell"><p className="font-bold">{item.studentName}</p><p className="text-xs text-slate-500">@{item.studentUserName}</p></td>}<td className="table-cell">{formatDate(item.submittedAtUtc)}</td><td className="table-cell"><SubmissionStatusBadge status={item.status}/></td><td className="table-cell"><span className="font-extrabold">{item.marks??"—"}</span> / {item.assignmentMaximumMarks}</td><td className="table-cell">{item.fileName?<span className="inline-flex max-w-40 items-center gap-1 truncate text-xs font-bold text-indigo-700"><Paperclip className="h-3.5 w-3.5 shrink-0"/>{item.fileName}</span>:<span className="text-slate-400">—</span>}</td><td className="table-cell"><p className="max-w-xs truncate text-sm text-slate-500">{item.feedback||"—"}</p></td>{mode==="teacher"&&<td className="table-cell text-right"><Button variant="secondary" size="sm" onClick={()=>openReview(item)}><Award className="h-4 w-4"/> Review</Button></td>}</tr>)}</tbody></table></div>}<Pagination page={page} totalPages={totalPages} totalCount={totalCount} onPageChange={setPage}/></Card>
 <Modal open={!!selected} onClose={()=>setSelected(null)} title="Review submission" description={`${selected?.studentName??"Student"} · ${selected?.assignmentTitle??"Assignment"}`} size="lg"><div className="mb-5 rounded-2xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Student answer</p><p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-slate-700">{selected?.answerText||"No written answer was provided."}</p>{selected?.fileName&&<div className="mt-4 flex flex-col gap-3 rounded-xl border border-indigo-100 bg-white p-3 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><p className="flex items-center gap-2 text-sm font-bold text-indigo-900"><Paperclip className="h-4 w-4"/> Attached answer file</p><p className="mt-1 truncate text-xs text-slate-600">{selected.fileName}</p></div><div className="flex gap-2"><Button type="button" variant="secondary" size="sm" loading={fileAction==="view"} onClick={()=>void handleFile("view")}><Eye className="h-4 w-4"/> View</Button><Button type="button" variant="secondary" size="sm" loading={fileAction==="download"} onClick={()=>void handleFile("download")}><Download className="h-4 w-4"/> Download</Button></div></div>}</div><form className="space-y-4" onSubmit={form.handleSubmit(review)}><div className="grid gap-4 sm:grid-cols-2"><div><label className="field-label">Marks (max {selected?.assignmentMaximumMarks})</label><Input type="number" step="0.01" {...form.register("marks")}/>{form.formState.errors.marks&&<p className="field-error">{form.formState.errors.marks.message}</p>}</div><div><label className="field-label">Status</label><Select {...form.register("status")}>{teacherReviewStatuses.map(value=><option key={value} value={value}>{submissionStatusLabel[value]}</option>)}</Select></div></div><div><label className="field-label">Feedback</label><Textarea className="min-h-36" placeholder="Provide clear and constructive feedback..." {...form.register("feedback")}/>{form.formState.errors.feedback&&<p className="field-error">{form.formState.errors.feedback.message}</p>}</div><div className="flex justify-end gap-3"><Button type="button" variant="secondary" onClick={()=>setSelected(null)}>Cancel</Button><Button type="submit" loading={form.formState.isSubmitting}><Award className="h-4 w-4"/> Save review</Button></div></form></Modal></>;
}
