-- Run this file while connected to assignment_management_db.
-- The API can also create the same tables automatically when Database:AutoCreate is true.

CREATE TABLE IF NOT EXISTS "Institutions" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" character varying(200) NOT NULL,
    "Code" character varying(30) NOT NULL,
    "Type" integer NOT NULL,
    "Address" character varying(500),
    "Email" character varying(100),
    "Phone" character varying(30),
    "LogoUrl" character varying(300),
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "CreatedByUserId" bigint,
    "UpdatedAtUtc" timestamp with time zone,
    "UpdatedByUserId" bigint,
    "IsActive" boolean NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Institutions_Code" ON "Institutions" ("Code");

CREATE TABLE IF NOT EXISTS "Roles" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" character varying(50) NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "CreatedByUserId" bigint,
    "UpdatedAtUtc" timestamp with time zone,
    "UpdatedByUserId" bigint,
    "IsActive" boolean NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Roles_Name" ON "Roles" ("Name");

CREATE TABLE IF NOT EXISTS "AcademicClasses" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" character varying(100) NOT NULL,
    "Section" character varying(50),
    "AcademicYear" character varying(30) NOT NULL,
    "InstitutionId" bigint NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "CreatedByUserId" bigint,
    "UpdatedAtUtc" timestamp with time zone,
    "UpdatedByUserId" bigint,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "FK_AcademicClasses_Institutions_InstitutionId"
        FOREIGN KEY ("InstitutionId") REFERENCES "Institutions" ("Id") ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS "IX_AcademicClasses_InstitutionId" ON "AcademicClasses" ("InstitutionId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_AcademicClasses_InstitutionId_Name_Section_AcademicYear"
    ON "AcademicClasses" ("InstitutionId", "Name", "Section", "AcademicYear");

CREATE TABLE IF NOT EXISTS "Subjects" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" character varying(120) NOT NULL,
    "Code" character varying(30) NOT NULL,
    "InstitutionId" bigint NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "CreatedByUserId" bigint,
    "UpdatedAtUtc" timestamp with time zone,
    "UpdatedByUserId" bigint,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "FK_Subjects_Institutions_InstitutionId"
        FOREIGN KEY ("InstitutionId") REFERENCES "Institutions" ("Id") ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS "IX_Subjects_InstitutionId" ON "Subjects" ("InstitutionId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Subjects_InstitutionId_Code"
    ON "Subjects" ("InstitutionId", "Code");

CREATE TABLE IF NOT EXISTS "Users" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FullName" character varying(100) NOT NULL,
    "Email" character varying(100) NOT NULL,
    "UserName" character varying(100) NOT NULL,
    "PasswordHash" text NOT NULL,
    "InstitutionId" bigint NOT NULL,
    "AcademicClassId" bigint,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "CreatedByUserId" bigint,
    "UpdatedAtUtc" timestamp with time zone,
    "UpdatedByUserId" bigint,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "FK_Users_Institutions_InstitutionId"
        FOREIGN KEY ("InstitutionId") REFERENCES "Institutions" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Users_AcademicClasses_AcademicClassId"
        FOREIGN KEY ("AcademicClassId") REFERENCES "AcademicClasses" ("Id") ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_Email" ON "Users" ("Email");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_UserName" ON "Users" ("UserName");
CREATE INDEX IF NOT EXISTS "IX_Users_InstitutionId" ON "Users" ("InstitutionId");
CREATE INDEX IF NOT EXISTS "IX_Users_AcademicClassId" ON "Users" ("AcademicClassId");

CREATE TABLE IF NOT EXISTS "UserRoles" (
    "UserId" bigint NOT NULL,
    "RoleId" bigint NOT NULL,
    CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_UserRoles_Users_UserId"
        FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserRoles_Roles_RoleId"
        FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_UserRoles_RoleId" ON "UserRoles" ("RoleId");

CREATE TABLE IF NOT EXISTS "RefreshTokens" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TokenHash" character varying(128) NOT NULL,
    "ExpiresAtUtc" timestamp with time zone NOT NULL,
    "RevokedAtUtc" timestamp with time zone,
    "ReplacedByTokenHash" character varying(128),
    "UserId" bigint NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "CreatedByUserId" bigint,
    "UpdatedAtUtc" timestamp with time zone,
    "UpdatedByUserId" bigint,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "FK_RefreshTokens_Users_UserId"
        FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_RefreshTokens_TokenHash" ON "RefreshTokens" ("TokenHash");
CREATE INDEX IF NOT EXISTS "IX_RefreshTokens_UserId" ON "RefreshTokens" ("UserId");

CREATE TABLE IF NOT EXISTS "TeacherClassSubjects" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TeacherId" bigint NOT NULL,
    "AcademicClassId" bigint NOT NULL,
    "SubjectId" bigint NOT NULL,
    "InstitutionId" bigint NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "CreatedByUserId" bigint,
    "UpdatedAtUtc" timestamp with time zone,
    "UpdatedByUserId" bigint,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "FK_TeacherClassSubjects_Users_TeacherId"
        FOREIGN KEY ("TeacherId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_TeacherClassSubjects_AcademicClasses_AcademicClassId"
        FOREIGN KEY ("AcademicClassId") REFERENCES "AcademicClasses" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_TeacherClassSubjects_Subjects_SubjectId"
        FOREIGN KEY ("SubjectId") REFERENCES "Subjects" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_TeacherClassSubjects_Institutions_InstitutionId"
        FOREIGN KEY ("InstitutionId") REFERENCES "Institutions" ("Id") ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_TeacherClassSubjects_TeacherId_AcademicClassId_SubjectId"
    ON "TeacherClassSubjects" ("TeacherId", "AcademicClassId", "SubjectId");
CREATE INDEX IF NOT EXISTS "IX_TeacherClassSubjects_AcademicClassId" ON "TeacherClassSubjects" ("AcademicClassId");
CREATE INDEX IF NOT EXISTS "IX_TeacherClassSubjects_SubjectId" ON "TeacherClassSubjects" ("SubjectId");
CREATE INDEX IF NOT EXISTS "IX_TeacherClassSubjects_InstitutionId" ON "TeacherClassSubjects" ("InstitutionId");

CREATE TABLE IF NOT EXISTS "Assignments" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Title" character varying(200) NOT NULL,
    "Description" text NOT NULL,
    "DeadlineUtc" timestamp with time zone NOT NULL,
    "MaximumMarks" numeric(10,2) NOT NULL,
    "Status" integer NOT NULL,
    "AllowResubmission" boolean NOT NULL,
    "InstitutionId" bigint NOT NULL,
    "TeacherClassSubjectId" bigint NOT NULL,
    "CreatedByTeacherId" bigint NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "CreatedByUserId" bigint,
    "UpdatedAtUtc" timestamp with time zone,
    "UpdatedByUserId" bigint,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "FK_Assignments_Institutions_InstitutionId"
        FOREIGN KEY ("InstitutionId") REFERENCES "Institutions" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Assignments_TeacherClassSubjects_TeacherClassSubjectId"
        FOREIGN KEY ("TeacherClassSubjectId") REFERENCES "TeacherClassSubjects" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Assignments_Users_CreatedByTeacherId"
        FOREIGN KEY ("CreatedByTeacherId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS "IX_Assignments_InstitutionId" ON "Assignments" ("InstitutionId");
CREATE INDEX IF NOT EXISTS "IX_Assignments_TeacherClassSubjectId" ON "Assignments" ("TeacherClassSubjectId");
CREATE INDEX IF NOT EXISTS "IX_Assignments_CreatedByTeacherId" ON "Assignments" ("CreatedByTeacherId");

CREATE TABLE IF NOT EXISTS "Submissions" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "AnswerText" text NOT NULL,
    "SubmittedAtUtc" timestamp with time zone NOT NULL,
    "Status" integer NOT NULL,
    "Marks" numeric(10,2),
    "Feedback" text,
    "ReviewedAtUtc" timestamp with time zone,
    "InstitutionId" bigint NOT NULL,
    "AssignmentId" bigint NOT NULL,
    "StudentId" bigint NOT NULL,
    "ReviewedByTeacherId" bigint,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "CreatedByUserId" bigint,
    "UpdatedAtUtc" timestamp with time zone,
    "UpdatedByUserId" bigint,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "FK_Submissions_Institutions_InstitutionId"
        FOREIGN KEY ("InstitutionId") REFERENCES "Institutions" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Submissions_Assignments_AssignmentId"
        FOREIGN KEY ("AssignmentId") REFERENCES "Assignments" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Submissions_Users_StudentId"
        FOREIGN KEY ("StudentId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Submissions_Users_ReviewedByTeacherId"
        FOREIGN KEY ("ReviewedByTeacherId") REFERENCES "Users" ("Id") ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Submissions_AssignmentId_StudentId"
    ON "Submissions" ("AssignmentId", "StudentId");
CREATE INDEX IF NOT EXISTS "IX_Submissions_InstitutionId" ON "Submissions" ("InstitutionId");
CREATE INDEX IF NOT EXISTS "IX_Submissions_StudentId" ON "Submissions" ("StudentId");
CREATE INDEX IF NOT EXISTS "IX_Submissions_ReviewedByTeacherId" ON "Submissions" ("ReviewedByTeacherId");

CREATE TABLE IF NOT EXISTS "ApplicationSettings" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Key" character varying(100) NOT NULL,
    "Value" text NOT NULL,
    "Description" character varying(300),
    "InstitutionId" bigint NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "CreatedByUserId" bigint,
    "UpdatedAtUtc" timestamp with time zone,
    "UpdatedByUserId" bigint,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "FK_ApplicationSettings_Institutions_InstitutionId"
        FOREIGN KEY ("InstitutionId") REFERENCES "Institutions" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_ApplicationSettings_InstitutionId_Key"
    ON "ApplicationSettings" ("InstitutionId", "Key");
