"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Pencil, Plus, Trash2, UserCog } from "lucide-react";
import { z } from "zod";
import { toast } from "sonner";
import { RolePage } from "@/components/auth/role-page";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { ConfirmDialog } from "@/components/ui/confirm-dialog";
import { EmptyState } from "@/components/ui/empty-state";
import { InlineLoader } from "@/components/ui/loading";
import { Modal } from "@/components/ui/modal";
import { PageHeader } from "@/components/ui/page-header";
import { Pagination } from "@/components/ui/pagination";
import { Select } from "@/components/ui/select";
import { adminService } from "@/lib/services";
import type { ClassResponse, SubjectResponse, TeacherAssignmentResponse, UserResponse } from "@/lib/types";
import { defaultPageSize } from "@/lib/constants";
import { errorMessage } from "@/lib/utils";

const schema = z.object({ teacherId: z.string().min(1, "Teacher is required"), academicClassId: z.string().min(1, "Class is required"), subjectId: z.string().min(1, "Subject is required"), isActive: z.boolean().default(true) });
type FormValues = z.infer<typeof schema>;

export default function TeacherAssignmentsPage() {
  const [items, setItems] = useState<TeacherAssignmentResponse[]>([]); const [teachers, setTeachers] = useState<UserResponse[]>([]); const [classes, setClasses] = useState<ClassResponse[]>([]); const [subjects, setSubjects] = useState<SubjectResponse[]>([]); const [loading, setLoading] = useState(true); const [page, setPage] = useState(1); const [totalPages, setTotalPages] = useState(0); const [totalCount, setTotalCount] = useState(0); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<TeacherAssignmentResponse|null>(null); const [target, setTarget] = useState<TeacherAssignmentResponse|null>(null); const [teacherFilter, setTeacherFilter] = useState(""); const [classFilter, setClassFilter] = useState(""); const [subjectFilter, setSubjectFilter] = useState("");
  const form = useForm<FormValues>({ resolver: zodResolver(schema), defaultValues: { teacherId: "", academicClassId: "", subjectId: "", isActive: true } });
  const load = useCallback(async () => { setLoading(true); try { const result = await adminService.getTeacherAssignments({ pageNumber: page, pageSize: defaultPageSize, teacherId: teacherFilter ? Number(teacherFilter) : undefined, academicClassId: classFilter ? Number(classFilter) : undefined, subjectId: subjectFilter ? Number(subjectFilter) : undefined }); setItems(result.items); setTotalPages(result.totalPages); setTotalCount(result.totalCount); } catch(e){toast.error(errorMessage(e));} finally {setLoading(false);} }, [classFilter,page,subjectFilter,teacherFilter]);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>{Promise.all([adminService.getUsers({pageNumber:1,pageSize:100,role:"Teacher",isActive:true}),adminService.getClasses(false),adminService.getSubjects(false)]).then(([u,c,s])=>{setTeachers(u.items);setClasses(c);setSubjects(s);}).catch(e=>toast.error(errorMessage(e)));},[]);
  const openForm=(item?:TeacherAssignmentResponse)=>{setEditing(item??null);form.reset(item?{teacherId:String(item.teacherId),academicClassId:String(item.academicClassId),subjectId:String(item.subjectId),isActive:item.isActive}:{teacherId:"",academicClassId:"",subjectId:"",isActive:true});setOpen(true);};
  const save=async(v:FormValues)=>{const payload={teacherId:Number(v.teacherId),academicClassId:Number(v.academicClassId),subjectId:Number(v.subjectId),isActive:v.isActive};try{if(editing)await adminService.updateTeacherAssignment(editing.id,payload);else await adminService.createTeacherAssignment(payload);toast.success(editing?"Teacher mapping updated":"Teacher assigned");setOpen(false);await load();}catch(e){toast.error(errorMessage(e));}};
  const deactivate=async()=>{if(!target)return;try{await adminService.deactivateTeacherAssignment(target.id);toast.success("Mapping deactivated");setTarget(null);await load();}catch(e){toast.error(errorMessage(e));}};
  return <RolePage role="Admin"><PageHeader title="Teacher mapping" description="Assign teachers to the correct class/course and subject." actions={<Button onClick={()=>openForm()}><Plus className="h-4 w-4"/> Assign teacher</Button>}/>
  <Card><div className="grid gap-3 border-b border-slate-100 p-4 md:grid-cols-3"><Select value={teacherFilter} onChange={e=>{setTeacherFilter(e.target.value);setPage(1);}}><option value="">All teachers</option>{teachers.map(x=><option key={x.id} value={x.id}>{x.fullName}</option>)}</Select><Select value={classFilter} onChange={e=>{setClassFilter(e.target.value);setPage(1);}}><option value="">All classes</option>{classes.map(x=><option key={x.id} value={x.id}>{x.name}{x.section?` - ${x.section}`:""}</option>)}</Select><Select value={subjectFilter} onChange={e=>{setSubjectFilter(e.target.value);setPage(1);}}><option value="">All subjects</option>{subjects.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select></div>
  {loading?<InlineLoader/>:items.length===0?<EmptyState title="No teacher mappings found" description="Assign a teacher to a class and subject to allow assignment creation."/>:<div className="overflow-x-auto"><table className="w-full min-w-[760px]"><thead className="table-head"><tr><th className="px-4 py-3">Teacher</th><th className="px-4 py-3">Class / course</th><th className="px-4 py-3">Subject</th><th className="px-4 py-3">Status</th><th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody>{items.map(item=><tr key={item.id} className="hover:bg-slate-50"><td className="table-cell"><div className="flex items-center gap-2"><UserCog className="h-4 w-4 text-indigo-600"/><span className="font-bold">{item.teacherName}</span></div></td><td className="table-cell">{item.className}</td><td className="table-cell">{item.subjectName}</td><td className="table-cell"><Badge tone={item.isActive?"emerald":"rose"}>{item.isActive?"Active":"Inactive"}</Badge></td><td className="table-cell"><div className="flex justify-end gap-2"><Button size="icon" variant="ghost" onClick={()=>openForm(item)}><Pencil className="h-4 w-4"/></Button>{item.isActive&&<Button size="icon" variant="ghost" onClick={()=>setTarget(item)}><Trash2 className="h-4 w-4 text-rose-600"/></Button>}</div></td></tr>)}</tbody></table></div>}<Pagination page={page} totalPages={totalPages} totalCount={totalCount} onPageChange={setPage}/></Card>
  <Modal open={open} onClose={()=>setOpen(false)} title={editing?"Edit teacher mapping":"Assign teacher"}><form className="space-y-4" onSubmit={form.handleSubmit(save)}><div><label className="field-label">Teacher</label><Select {...form.register("teacherId")}><option value="">Select teacher</option>{teachers.map(x=><option key={x.id} value={x.id}>{x.fullName} (@{x.userName})</option>)}</Select>{form.formState.errors.teacherId&&<p className="field-error">{form.formState.errors.teacherId.message}</p>}</div><div><label className="field-label">Class / course</label><Select {...form.register("academicClassId")}><option value="">Select class</option>{classes.map(x=><option key={x.id} value={x.id}>{x.name}{x.section?` - ${x.section}`:""} ({x.academicYear})</option>)}</Select>{form.formState.errors.academicClassId&&<p className="field-error">{form.formState.errors.academicClassId.message}</p>}</div><div><label className="field-label">Subject</label><Select {...form.register("subjectId")}><option value="">Select subject</option>{subjects.map(x=><option key={x.id} value={x.id}>{x.name} ({x.code})</option>)}</Select>{form.formState.errors.subjectId&&<p className="field-error">{form.formState.errors.subjectId.message}</p>}</div>{editing&&<label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" {...form.register("isActive")}/> Active mapping</label>}<div className="flex justify-end gap-3"><Button type="button" variant="secondary" onClick={()=>setOpen(false)}>Cancel</Button><Button type="submit" loading={form.formState.isSubmitting}>Save mapping</Button></div></form></Modal>
  <ConfirmDialog open={!!target} onClose={()=>setTarget(null)} onConfirm={deactivate} title="Deactivate teacher mapping" description={`This teacher will no longer be able to create new assignments for ${target?.className??"this class"} and ${target?.subjectName??"subject"}.`} confirmText="Deactivate"/></RolePage>;
}
