"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, CalendarClock, CheckCircle2, ClipboardCheck, Edit3, FileText, LockKeyhole, Send, Trash2, UserRound } from "lucide-react";
import { toast } from "sonner";
import { AssignmentStatusBadge, SubmissionStatusBadge } from "@/components/common/status-badges";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { ConfirmDialog } from "@/components/ui/confirm-dialog";
import { EmptyState } from "@/components/ui/empty-state";
import { InlineLoader } from "@/components/ui/loading";
import { PageHeader } from "@/components/ui/page-header";
import { assignmentService, submissionService } from "@/lib/services";
import { AssignmentStatus, type AssignmentResponse, type SubmissionResponse } from "@/lib/types";
import { deadlineState, errorMessage, formatDate } from "@/lib/utils";

export function AssignmentDetail({ id, mode }: { id: number; mode: "admin" | "teacher" }) {
  const router=useRouter(); const[item,setItem]=useState<AssignmentResponse|null>(null); const[submissions,setSubmissions]=useState<SubmissionResponse[]>([]); const[loading,setLoading]=useState(true); const[action,setAction]=useState<"publish"|"draft"|"close"|"delete"|null>(null); const[working,setWorking]=useState(false);
  const load=useCallback(async()=>{setLoading(true);try{const[a,s]=await Promise.all([assignmentService.getById(id),submissionService.get({assignmentId:id,pageNumber:1,pageSize:10})]);setItem(a);setSubmissions(s.items);}catch(e){toast.error(errorMessage(e));}finally{setLoading(false);}},[id]);useEffect(()=>{void load();},[load]);
  const execute=async()=>{if(!action)return;setWorking(true);try{if(action==="publish")await assignmentService.publish(id);if(action==="draft")await assignmentService.moveToDraft(id);if(action==="close")await assignmentService.close(id);if(action==="delete")await assignmentService.remove(id);toast.success(action==="delete"?"Assignment deleted":`Assignment moved to ${action}`);setAction(null);if(action==="delete")router.push("/teacher/assignments");else await load();}catch(e){toast.error(errorMessage(e));}finally{setWorking(false);}};
  if(loading)return <InlineLoader label="Loading assignment..."/>; if(!item)return <Card><EmptyState title="Assignment not found"/></Card>; const deadline=deadlineState(item.deadlineUtc);
  return <><PageHeader title={item.title} description={`${item.subjectName} · ${item.className}${item.section?` · ${item.section}`:""}`} actions={<><Button variant="secondary" onClick={()=>router.back()}><ArrowLeft className="h-4 w-4"/> Back</Button>{mode==="teacher"&&<Link href={`/teacher/assignments/${id}/edit`}><Button variant="secondary"><Edit3 className="h-4 w-4"/> Edit</Button></Link>}</>}/>
  <div className="grid gap-6 xl:grid-cols-[1.5fr_.8fr]"><Card><CardHeader className="flex flex-row items-start justify-between gap-3"><div><p className="text-sm font-semibold text-slate-500">Assignment details</p><h2 className="mt-1 text-xl font-extrabold">{item.title}</h2></div><AssignmentStatusBadge status={item.status}/></CardHeader><CardContent><div className="whitespace-pre-wrap text-sm leading-7 text-slate-700">{item.description}</div><div className="mt-6 grid gap-3 border-t border-slate-100 pt-5 sm:grid-cols-2"><Info icon={CalendarClock} label="Deadline" value={`${formatDate(item.deadlineUtc)} (${deadline.label})`}/><Info icon={CheckCircle2} label="Maximum marks" value={`${item.maximumMarks}`}/><Info icon={UserRound} label="Teacher" value={item.teacherName}/><Info icon={ClipboardCheck} label="Resubmission" value={item.allowResubmission?"Allowed before deadline":"Not allowed"}/></div>{mode==="teacher"&&<div className="mt-6 flex flex-wrap gap-2 border-t border-slate-100 pt-5">{item.status===AssignmentStatus.Draft&&<Button onClick={()=>setAction("publish")}><Send className="h-4 w-4"/> Publish</Button>}{item.status===AssignmentStatus.Published&&<><Button variant="secondary" onClick={()=>setAction("draft")}><FileText className="h-4 w-4"/> Move to draft</Button><Button variant="danger" onClick={()=>setAction("close")}><LockKeyhole className="h-4 w-4"/> Close</Button></>}{item.submissionCount===0&&<Button variant="ghost" onClick={()=>setAction("delete")}><Trash2 className="h-4 w-4 text-rose-600"/> Delete</Button>}</div>}</CardContent></Card>
  <Card><CardHeader><h2 className="font-extrabold">Summary</h2></CardHeader><CardContent className="space-y-4"><div className="rounded-2xl bg-indigo-50 p-4"><p className="text-sm font-semibold text-indigo-600">Submissions received</p><p className="mt-1 text-3xl font-black text-indigo-900">{item.submissionCount}</p></div><div><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Class / course</p><p className="mt-1 font-bold text-slate-800">{item.className}{item.section?` · ${item.section}`:""}</p></div><div><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Subject</p><p className="mt-1 font-bold text-slate-800">{item.subjectName}</p></div><div><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Created</p><p className="mt-1 font-semibold text-slate-700">{formatDate(item.createdAtUtc)}</p></div></CardContent></Card></div>
  <Card className="mt-6"><CardHeader className="flex flex-row items-center justify-between"><div><h2 className="font-extrabold">Recent submissions</h2><p className="mt-1 text-sm text-slate-500">Latest answers received for this assignment.</p></div><Link href={`/${mode}/submissions?assignmentId=${id}`} className="text-sm font-bold text-indigo-600">View all</Link></CardHeader>{submissions.length===0?<EmptyState title="No submissions yet"/>:<div className="overflow-x-auto"><table className="w-full min-w-[700px]"><thead className="table-head"><tr><th className="px-4 py-3">Student</th><th className="px-4 py-3">Submitted</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Marks</th></tr></thead><tbody>{submissions.map(s=><tr key={s.id}><td className="table-cell"><p className="font-bold">{s.studentName}</p><p className="text-xs text-slate-500">@{s.studentUserName}</p></td><td className="table-cell">{formatDate(s.submittedAtUtc)}</td><td className="table-cell"><SubmissionStatusBadge status={s.status}/></td><td className="table-cell font-bold">{s.marks??"—"} / {s.assignmentMaximumMarks}</td></tr>)}</tbody></table></div>}</Card>
  <ConfirmDialog open={!!action} onClose={()=>setAction(null)} onConfirm={execute} loading={working} title={`${action?.[0]?.toUpperCase()??""}${action?.slice(1)??""} assignment`} description={action==="delete"?"This permanently removes the assignment. This action cannot be undone.":`Confirm that you want to ${action} this assignment.`} confirmText={action??"Confirm"} danger={action==="delete"||action==="close"}/></>;
}
function Info({icon:Icon,label,value}:{icon:React.ComponentType<{className?:string}>;label:string;value:string}){return <div className="flex gap-3 rounded-xl bg-slate-50 p-3"><Icon className="mt-0.5 h-5 w-5 text-indigo-600"/><div><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-1 text-sm font-bold text-slate-800">{value}</p></div></div>}
